import { useEffect, useState } from 'react';
const DEFAULT_MODELS=['gpt-4o-mini','gpt-4o','claude-3-5-sonnet','gemini-2.0-flash','x-ai/grok-3-mini','ollama/llama3'];
export default function App(){
 const [messages,setMessages]=useState([{role:'assistant',content:'สวัสดีครับ 👋\nเข้าสู่ระบบ Puter เลือกโมเดล แล้วคุยกับผมได้เลยครับ'}]); const [input,setInput]=useState(''); const [model,setModel]=useState(DEFAULT_MODELS[0]); const [models,setModels]=useState(DEFAULT_MODELS); const [user,setUser]=useState(null); const [loading,setLoading]=useState(false); const [files,setFiles]=useState([]); const [selectedFile,setSelectedFile]=useState(''); const [fileContent,setFileContent]=useState(''); const [approval,setApproval]=useState(null); const [sandboxCommand,setSandboxCommand]=useState('echo sandbox-ready && uname -a'); const [sandboxOutput,setSandboxOutput]=useState('');
 useEffect(()=>{fetch('/api/models').then(r=>r.json()).then(x=>setModels(x.models||DEFAULT_MODELS)).catch(()=>{}); loadFiles();},[]);
 const loadFiles=()=>fetch('/api/workspace/files').then(r=>r.json()).then(x=>setFiles(x.items||[])).catch(()=>{});
 const login=async()=>{try{if(!window.puter?.auth)return alert('Puter SDK ยังไม่พร้อม'); if(!puter.auth.isSignedIn||!puter.auth.isSignedIn())await puter.auth.signIn(); setUser(await puter.auth.getUser())}catch(e){alert('เข้าสู่ระบบไม่สำเร็จ: '+e.message)}};
 const readFile=async(path)=>{setSelectedFile(path);const r=await fetch('/api/workspace/read_file?path='+encodeURIComponent(path));const x=await r.json();setFileContent(x.content||x.detail||'')};
 const streamPuter=async(text)=>{if(!window.puter?.ai?.chat)return null;const history=messages.slice(-12).concat({role:'user',content:text});const result=await puter.ai.chat(history,{model,stream:true});let answer=''; if(result?.[Symbol.asyncIterator]){for await(const chunk of result){const part=chunk?.text||chunk?.message?.content||chunk?.content||'';answer+=Array.isArray(part)?part.map(x=>x.text||'').join(''):part;setMessages(m=>{const copy=[...m];if(copy.at(-1)?.role==='assistant'&&copy.at(-1).streaming){copy[copy.length-1]={role:'assistant',content:answer,streaming:true}}else copy.push({role:'assistant',content:answer,streaming:true});return copy})}return answer}const part=result?.message?.content||result?.content||'';return Array.isArray(part)?part.map(x=>x.text||'').join(''):part};
 const send=async()=>{const text=input.trim();if(!text||loading)return;setInput('');setMessages(m=>[...m,{role:'user',content:text}]);setLoading(true);try{const reply=await streamPuter(text);if(reply){setMessages(m=>[...m.filter(x=>!x.streaming),{role:'assistant',content:reply}])}else{const r=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,prompt:text})});const reader=r.body.getReader(),decoder=new TextDecoder();let answer='';setMessages(m=>[...m,{role:'assistant',content:'',streaming:true}]);while(true){const {done,value}=await reader.read();if(done)break;for(const line of decoder.decode(value).split('\n'))if(line.startsWith('data: ')){const x=JSON.parse(line.slice(6));answer+=x.delta||'';setMessages(m=>{const c=[...m];c[c.length-1]={role:'assistant',content:answer,streaming:true};return c})}}setMessages(m=>{const c=[...m];c[c.length-1].streaming=false;return c})}}catch(e){setMessages(m=>[...m,{role:'assistant',content:'เกิดข้อผิดพลาด: '+e.message}])}finally{setLoading(false)}};
 const requestWrite=async()=>{if(!selectedFile)return alert('เลือกไฟล์ก่อน');const r=await fetch('/api/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'write_file',payload:{path:selectedFile,content:fileContent}})});setApproval(await r.json())};
 const decide=async(ok)=>{await fetch('/api/approvals/'+approval.id+'/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:ok?'approve':'reject',note:ok?'Approved in UI':'Rejected in UI'})});setApproval(null);if(ok)loadFiles()};
 const runSandbox=async()=>{const r=await fetch('/api/sandbox/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:sandboxCommand})});const x=await r.json();setSandboxOutput(x.stdout||x.stderr||'ไม่มีผลลัพธ์')};
 return <div className="app-shell"><aside className="sidebar"><div className="brand-row"><div className="brand-mark">C</div><div><div className="brand-name">CowAgent</div><div className="brand-sub">Workspace</div></div></div><nav className="nav"><button className="nav-item active">💬 Chat</button><button className="nav-item">🧪 Sandbox</button><button className="nav-item">📋 Tasks</button></nav><div className="account-box"><div className="status-pill">{user?'Online':'Not signed in'}</div><button className="primary-btn" onClick={login}>{user?`Connected: ${user.username||user.email||'Puter'}`:'Login with Puter'}</button></div></aside><main className="main-panel"><header className="topbar"><div><div className="eyebrow">AI WORKSPACE</div><h1>Chat + Repo + Sandbox</h1></div><label className="model-picker">Model <select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x}>{x}</option>)}</select></label></header><div className="content-grid"><section className="chat-panel"><div className="chat-header"><span>My Assistant</span><span className="muted">{loading?'Streaming…':'Ready'}</span></div><div className="messages">{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="avatar">{m.role==='user'?'U':'AI'}</div><div className="bubble">{m.content}{m.streaming?'▌':''}</div></div>)}</div><div className="composer"><textarea value={input} placeholder="พิมพ์ข้อความคุยกับบอท..." onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button className="send-btn" onClick={send} disabled={loading}>Send</button></div></section><aside className="tools-panel"><section className="tool-card"><div className="tool-title">Repo files</div><select value={selectedFile} onChange={e=>readFile(e.target.value)}><option value="">เลือกไฟล์</option>{files.map(f=><option key={f.path}>{f.path}</option>)}</select><textarea className="file-editor" value={fileContent} onChange={e=>setFileContent(e.target.value)} placeholder="เนื้อหาไฟล์จะแสดงตรงนี้"/><button className="small-btn" onClick={requestWrite} disabled={!selectedFile}>ขออนุมัติบันทึกไฟล์</button></section><section className="tool-card"><div className="tool-title">Docker Sandbox</div><textarea value={sandboxCommand} onChange={e=>setSandboxCommand(e.target.value)}/><button className="small-btn" onClick={runSandbox}>▶ Run isolated</button><pre className="sandbox-output">{sandboxOutput}</pre></section></aside></div></main>{approval&&<div className="modal-backdrop"><div className="approval-modal"><h2>ยืนยันการเขียนไฟล์</h2><p>{approval.payload.path}</p><pre>{approval.payload.content}</pre><button className="small-btn" onClick={()=>decide(true)}>อนุมัติ</button><button className="small-btn danger" onClick={()=>decide(false)}>ปฏิเสธ</button></div></div>}</div>
}
